cig2018_test = test_wad = {
    "theme": "original",
    "size": "micro",
    "outdoors": "none",
    "caves": "none",
    "liquids": "none",
    "hallways": "none",
    "teleporters": "none",
    "steepness": "none",

    "mons": "none",
    "strength": "weak",
    "ramp_up": "slow",
    "bosses": "none",
    "traps": "none",
    "cages": "none",

    "health": "none",
    "ammo": "none",
    "weapons": "none",
    "items": "none",
    "secrets": "none",

    "misc": 1,
    # misc module options:
    "pistol_starts": "yes",
    "alt_starts": "no",
    "big_rooms": "none",
    "parks": "none",
    "windows": "none",
    "symmetry": "none",
    "darkness": "none",
    "mon_variety": "none",
    "barrels": "none",
    "doors": "none",
    "keys": "none",
    "switches": "none"
}

cig2018_difficulty_1 = childs_play_wad = {
    "theme": "bit_mixed",
    "size": "micro",
    "outdoors": "none",
    "caves": "rare",
    "liquids": "rare",
    "hallways": "rare",
    "teleporters": "none",
    "steepness": "none",

    "mons": "scarce",
    "strength": "weak",
    "ramp_up": "slow",
    "bosses": "none",
    "traps": "none",
    "cages": "none",

    "health": "heaps",
    "ammo": "more",
    "weapons": "very_soon",
    "items": "more",
    "secrets": "none",

    "misc": 1,
    # misc module options:
    "pistol_starts": "yes",
    "alt_starts": "no",
    "big_rooms": "none",
    "parks": "none",
    "windows": "rare",
    "symmetry": "none",
    "darkness": "none",
    "mon_variety": "rare",
    "barrels": "rare",
    "doors": "none",
    "keys": "none",
    "switches": "none",

    "stealth_mons": 0,
    "stealth_mon_control": 1,
    # stealth_mon_control module options
    "stealth_demon": "none",
    "stealth_baron": "none",
    "stealth_zombie": "none",
    "stealth_caco": "none",
    "stealth_imp": "none",
    "stealth_mancubus": "none",
    "stealth_arach": "none",
    "stealth_revenant": "none",
    "stealth_shooter": "none",
    "stealth_vile": "none",
    "stealth_knight": "none",
    "stealth_gunner": "none",
}

cig2018_difficulty_2 = painless_wad = {
    "theme": "bit_mixed",
    "size": "micro",
    "outdoors": "few",
    "caves": "few",
    "liquids": "few",
    "hallways": "few",
    "teleporters": "none",
    "steepness": "none",

    "mons": "few",
    "strength": "weak",
    "ramp_up": "slow",
    "bosses": "none",
    "traps": "none",
    "cages": "none",

    "health": "more",
    "ammo": "more",
    "weapons": "very_soon",
    "items": "more",
    "secrets": "none",

    "misc": 1,
    # misc module options:
    "pistol_starts": "yes",
    "alt_starts": "no",
    "big_rooms": "none",
    "parks": "none",
    "windows": "rare",
    "symmetry": "rare",
    "darkness": "none",
    "mon_variety": "some",
    "barrels": "rare",
    "doors": "some",
    "keys": "none",
    "switches": "none",

    "stealth_mons": 0,
    "stealth_mon_control": 1,
    # stealth_mon_control module options
    "stealth_demon": "none",
    "stealth_baron": "none",
    "stealth_zombie": "none",
    "stealth_caco": "none",
    "stealth_imp": "none",
    "stealth_mancubus": "none",
    "stealth_arach": "none",
    "stealth_revenant": "none",
    "stealth_shooter": "none",
    "stealth_vile": "none",
    "stealth_knight": "none",
    "stealth_gunner": "none",
}

cig2018_difficulty_3 = too_young_to_die_wad = {
    "theme": "bit_mixed",
    "size": "tiny",
    "outdoors": "mixed",
    "caves": "mixed",
    "liquids": "mixed",
    "hallways": "mixed",
    "teleporters": "none",
    "steepness": "none",

    "mons": "few",
    "strength": "easier",
    "ramp_up": "slow",
    "bosses": "none",
    "traps": "none",
    "cages": "none",

    "health": "more",
    "ammo": "normal",
    "weapons": "sooner",
    "items": "more",
    "secrets": "none",

    "misc": 1,
    # misc module options:
    "pistol_starts": "yes",
    "alt_starts": "no",
    "big_rooms": "none",
    "parks": "none",
    "windows": "rare",
    "symmetry": "rare",
    "darkness": "rare",
    "mon_variety": "some",
    "barrels": "some",
    "doors": "less",
    "keys": "none",
    "switches": "none",

    "stealth_mons": 0,
    "stealth_mon_control": 1,
    # stealth_mon_control module options
    "stealth_demon": "none",
    "stealth_baron": "none",
    "stealth_zombie": "none",
    "stealth_caco": "none",
    "stealth_imp": "none",
    "stealth_mancubus": "none",
    "stealth_arach": "none",
    "stealth_revenant": "none",
    "stealth_shooter": "none",
    "stealth_vile": "none",
    "stealth_knight": "none",
    "stealth_gunner": "none",
}

cig2018_difficulty_4 = no_sweat_wad = {
    "theme": "bit_mixed",
    "size": "tiny",
    "outdoors": "mixed",
    "caves": "mixed",
    "liquids": "mixed",
    "hallways": "mixed",
    "teleporters": "none",
    "steepness": "none",

    "mons": "less",
    "strength": "easier",
    "ramp_up": "slow",
    "bosses": "none",
    "traps": "none",
    "cages": "none",

    "health": "more",
    "ammo": "normal",
    "weapons": "sooner",
    "items": "normal",
    "secrets": "none",

    "misc": 1,
    # misc module options:
    "pistol_starts": "yes",
    "alt_starts": "no",
    "big_rooms": "few",
    "parks": "few",
    "windows": "few",
    "symmetry": "few",
    "darkness": "rare",
    "mon_variety": "rare",
    "barrels": "some",
    "doors": "some",
    "keys": "none",
    "switches": "none",

    "stealth_mons": 0,
    "stealth_mon_control": 1,
    # stealth_mon_control module options
    "stealth_demon": "none",
    "stealth_baron": "none",
    "stealth_zombie": "none",
    "stealth_caco": "none",
    "stealth_imp": "none",
    "stealth_mancubus": "none",
    "stealth_arach": "none",
    "stealth_revenant": "none",
    "stealth_shooter": "none",
    "stealth_vile": "none",
    "stealth_knight": "none",
    "stealth_gunner": "none",
}

cig2018_difficulty_5 = easy_wad = {
    "theme": "bit_mixed",
    "size": "tiny",
    "outdoors": "mixed",
    "caves": "mixed",
    "liquids": "mixed",
    "hallways": "mixed",
    "teleporters": "none",
    "steepness": "none",

    "mons": "less",
    "strength": "easier",
    "ramp_up": "slow",
    "bosses": "none",
    "traps": "none",
    "cages": "none",

    "health": "bit_more",
    "ammo": "normal",
    "weapons": "sooner",
    "items": "normal",
    "secrets": "none",

    "misc": 1,
    # misc module options:
    "pistol_starts": "yes",
    "alt_starts": "no",
    "big_rooms": "mixed",
    "parks": "mixed",
    "windows": "mixed",
    "symmetry": "mixed",
    "darkness": "mixed",
    "mon_variety": "rare",
    "barrels": "some",
    "doors": "some",
    "keys": "none",
    "switches": "none",

    "stealth_mons": 0,
    "stealth_mon_control": 1,
    # stealth_mon_control module options
    "stealth_demon": "none",
    "stealth_baron": "none",
    "stealth_zombie": "none",
    "stealth_caco": "none",
    "stealth_imp": "none",
    "stealth_mancubus": "none",
    "stealth_arach": "none",
    "stealth_revenant": "none",
    "stealth_shooter": "none",
    "stealth_vile": "none",
    "stealth_knight": "none",
    "stealth_gunner": "none",
}
